pknu-wap/StarList

server/src/main/java/wap/starlist/controller/BookmarkController.java, server/src/main/java/wap/starlist/domain/Bookmark.java, server/src/main/java/wap/starlist/dto/request/BookmarkCreateRequest.java, server/src/main/java/wap/starlist/dto/response/BookmarkErrorResponse.java, server/src/main/java/wap/starlist/dto/response/BookmarkResponse.java, server/src/main/java/wap/starlist/service/BookmarkService.java, server/src/main/resources/application.properties
Closed #5 
- 북마크 생성 기능 추가
- Request/Response 객체 생성
- 북마크 생성 api 명세 변경
- 북마크 1개 조회 api 명세 추가
- 북마크가 생성되면 저장된 위치를 반환한다. 이 위치는 `/bookmarks/{id}`이다. 이는 `ResponseEntity.created(URI uri)`를 사용하기 위해서 찾아보았으며  유용하게 사용될 듯하여 추가하였다.
- 생성 시 `dateAdded`는 바로 저장되게 했으며, 나머지 필드의 값은 이후 추가하도록 하겠다.
- 북마크 1개만 조회하는 기능이 빠져있어 추가하였다. 북마크 생성이 올바르게 작동하는지 테스트할 수 있고, 웹에서 북마크를 클릭했을 때 뜨는 팝업페이지에서 사용될 수도 있을것 같아 만들었다.
- 존재하지 않는 `id`에 대해 조회할 시 400 응답을 보낸다.
리뷰어가 알아야 할 추가 정보가 있다면 적어주세요 (ex: 주의할 점, 트러블슈팅 등) 
- ai 관련 작업은 추후 개발하도록 하겠다.
- 북마크 관련 예외 응답은 `BookmarkErrorResponse`를 사용하자.
- 시간 정보를 `Long`으로 변경하였습니다.
- 엔티티 관련 모든 변경사항은 ERD에 적용하여 새롭게 업데이트 하였습니다.
=> 북마크 생성 기능 추가

server/src/main/java/wap/starlist/controller/FolderController.java, server/src/main/java/wap/starlist/domain/Folder.java, server/src/main/java/wap/starlist/dto/request/FolderCreateRequest.java, server/src/main/java/wap/starlist/dto/response/FolderErrorResponse.java, server/src/main/java/wap/starlist/dto/response/FolderResponse.java, server/src/main/java/wap/starlist/service/FolderService.java
- 폴더를 생성하는 기능을 구현함.
- 사용자는 생성된 폴더에 북마크를 넣어둘 수 있음.
#7 
- 폴더 제목(title)과 사용자ID(userId) 정보를 저장함.
- 필수값인 폴더 제목(title)과 사용자ID(userId)가 존재하는지 검사함.
- 응답을 클라이언트에 반환함.
- `FolderController`
- `Post /folders` 엔드포인트 추가
- `id`로 폴더 조회하는 메서드 추가
- `FolderCreateRequest`
- 폴더 생성 요청 DTO 클래스
- `FolderErrorResponse`, `FolderResponse`
- 폴더 생성 응답 DTO 클래스
- `FolderService`
- 폴더 생성 메서드 추가
- 필수값(title, userId) 검증
- 기능 구현이 정상적으로 되었는지 확인해 주세요!!
- 개선하면 좋을 부분을 말해주세요!!
- 백엔드 개발은 처음이라 북마크 생성 API와 ChatGP, 구글을 참고하며 구현했습니다.
- 그래서 미흡한 부분이 많은 점 참고 바랍니다!!
=> 폴더 생성 기능 개발

server/src/main/java/wap/starlist/controller/FolderController.java, server/src/main/java/wap/starlist/service/FolderService.java
- 폴더 생성 코드를 develop 브랜치에 merge할 때 불필요한 코드가 반영되어 이를 삭제함.
Resolve : #7 
- 폴더 생성 API 구현 후 feature/create-folder 브랜치를 develop 브랜치에 merge하는 과정에서 불필요한 코드가 함께 올라가 버림.
- 이에 해당 코드를 삭제하기 위해 fix/remove-bad-code 브랜치를 생성했고, 이를 develop 브랜치에 merge할 예정임
+) 원래는 develop 브랜치에서 바로 작업하려 했으나 뭔가 잘 안 돼서 그냥 브랜치 새로 생성함.
- FolderController.java 파일의 deleteFolder 메서드 삭제
- FolderService.java 파일의 deleteFolder 메서드 삭제
=> 잘못 Merge된 코드 삭제

extension/src/popup/components/Logo.jsx, extension/src/popup/components/Text.jsx
범용 컴포넌트인 Logo.jsx, Text.jsx 를 구현하였습니다.
Resolve : #28
- 모든 페이지에서 사용하는 범용 컴포넌트들 중에서  `Logo.jsx`, `Text.jsx` 컴포넌트를 구현하였습니다.
-  `Logo.jsx`, `Text.jsx` : 파일 생성 및 코드를 작성하였습니다.
=> feat: 범용 컴포넌트 구현

server/src/main/java/wap/starlist/controller/FolderController.java, server/src/main/java/wap/starlist/service/FolderService.java
Resolve : #10 
- 생성된 폴더를 삭제하는 기능을 구현했습니다.
- `FolderController`
- `/folders/{id}` 엔드포인트 추가
- 폴더가 존재하지 않을 경우 에러메시지 반환
- 삭제 성공 시 `204 No Content` 반환
- `FolderService`
- 폴더 삭제 메서드 추가
- 대상 폴더 조회 후 삭제 진행
=> 폴더 삭제 기능 개발

server/src/main/resources/application.properties
=> chore: delete server/src/main/resources/application.properties

extension/public/manifest.json, extension/src/popup/components/SyncButton.jsx, extension/src/popup/hooks/useNavigation.js, extension/src/popup/pages/SyncStartPage.jsx, extension/src/popup/pages/SyncStatusPage.jsx, extension/src/service_worker/service_worker.js
=> feat: 동기화 시작 버튼 구현

server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java, server/src/main/java/wap/starlist/bookmark/dto/request/BookmarksDeleteRequest.java, server/src/main/java/wap/starlist/bookmark/dto/response/BookmarksDeleteErrorResponse.java, server/src/main/java/wap/starlist/bookmark/dto/response/BookmarksDeleteResponse.java, server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
Resolve : #33
- 선택된 북마크를 삭제하는 기능을 구헌했습니다.
- 삭제되는 북마크는 1개 이상입니다.
- `BookmarkDeleteRequest`
- 북마크 삭제 요청용 DTO를 추가했습니다.
- `BookmarkDeleteResponse`
- 북마크 삭제 응답용 DTO를 추가했습니다.
- 삭제 성공 시의 DTO입니다.
- `BookmarkDeleteErrorResponse`
- 북마크 삭제 실패 시의 응답 DTO입니다.
- `BookmarkController`
- 북마크 삭제 엔드포인트를 추가했습니다.
- 삭제 성공 시 그 결과인 `code`, `message`, `count`를 반환합니다.
- `BookmarkService`
- 북마크 일괄 삭제 메서드를 추가했습니다.
- 삭제를 원하는 북마크가 존재하는지 id로 조회한 후 일괄 삭제합니다.
- 삭제된 북마크 개수를 반환합니다.
=> 북마크 삭제 기능 구현

client/src/store/useAuthStore.js
- 메인화면 테스트를 위해서 isLoggedIn 변수를 true로 바꾼 것을 다시 false로 복구함
=> fix: useAuthStore 버그 수정

server/src/main/java/wap/starlist/config/auth/handler/OAuth2SuccessHandler.java
=> 토큰을 client로 redirect하여 쿼리파마리터로 전송하도록 변경

server/src/main/java/wap/starlist/config/auth/dto/UserInfoResponse.java, server/src/main/java/wap/starlist/member/MemberController.java, server/src/main/java/wap/starlist/member/MemberService.java, server/src/main/java/wap/starlist/member/domain/Member.java, server/src/main/java/wap/starlist/member/repository/MemberRepository.java
=> 로그인된 사용자의 동기화 여부를 확인할 수 있는 기능

client/src/App.jsx
Resolve : #36 
login 페이지를 없애면서 발생한 404오류를 라우팅을 수정하여 해결
=> fix: 페이지 라우팅 수정

client/netlify.toml
=> chore: toml파일 제거

server/src/main/java/wap/starlist/config/SecurityConfig.java
=> CORS 설정 추가

server/src/main/java/wap/starlist/auth/JwtTokenProvider.java, server/src/main/java/wap/starlist/auth/constants/AuthConstants.java, server/src/main/java/wap/starlist/auth/dto/OAuth2UserPrincipal.java, server/src/main/java/wap/starlist/auth/dto/UserInfoResponse.java, server/src/main/java/wap/starlist/auth/dto/UserRole.java, server/src/main/java/wap/starlist/auth/security/OAuth2SuccessHandler.java, server/src/main/java/wap/starlist/auth/security/TokenAuthenticationFilter.java, server/src/main/java/wap/starlist/auth/service/CustomOAuth2UserService.java, server/src/main/java/wap/starlist/config/SecurityConfig.java, server/src/main/java/wap/starlist/member/domain/Member.java
auth 패키지의 구조가 어수선하고 가독성이 떨어져 기능별로 구분하였습니다.
개선의 여지나 오타가 있다면 말씀 부탁드려요.
반드시 `rebase`를 해야합니다!!!!
```bash
git checkout main
git pull origin main
git checkout feature/login
git rebase main
```
=> auth 패키지 구조 기능별로 구분되도록 변경

extension/src/popup/App.jsx, extension/src/popup/hooks/useNavigation.js, extension/src/popup/pages/SyncStartPage.jsx, extension/src/popup/pages/SyncStatusPage.jsx, extension/src/service_worker/service_worker.js
Resolve : #
- 중간 발표 전에 수정했던 라우팅 관련 작업 내용이 반영이 안되어있어서 추가합니다.
- `App.jsx` : 라우팅 관련 오타를 수정
- `useNavigation.js` : 라우팅 관련 오타를 수정
- `service_worker.js` : 웹페이지에서 전송한 메시지를 수신하는 로직에서 현재 적용되지 않은 부분은 잠시 주석 처리함
- `SyncStartPage.jsx`, `SyncStatusPage.jsx` : 현재 헤더 사용을 안하고 있어 잠시 주석 처리함
=> chore: 중간발표 전 작업

server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java, server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkTreeNode.java, server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
=> 로그 확인을 위해 주석 작성

server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java, server/src/main/java/wap/starlist/bookmark/domain/Bookmark.java, server/src/main/java/wap/starlist/bookmark/domain/Folder.java, server/src/main/java/wap/starlist/bookmark/domain/Root.java, server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkTreeNode.java, server/src/main/java/wap/starlist/bookmark/repository/RootRepository.java, server/src/main/java/wap/starlist/bookmark/service/RootService.java
Resolve : #72 
- GET 요청을 받는 컨트롤러 구현
- Root 엔티티를 `BookmarkTreeNode` 트리 구조로 변경한다. 
- dfs 를 통해 순회하고 Root, Folder, Bookmark를 `BookmarkTreeNode`로 변경한다.
- 사용자의 google provider id에 매핑된 Root를 가져오는 쿼리를 작성하였다.
=> 사용자와 관련된 모든 북마크를 가져오는 기능 추가

client/src/pages/AuthSuccessPage.jsx, client/src/pages/MainPage.jsx
이후 리프레시 토큰 추가 시 변수명에 혼동이 없도록 jwt, token 등의 이름에서 access로 통합 및 변경
=> token 변수 명칭 변경

extension/public/manifest.json, extension/src/service_worker/service_worker.js
Resolve : #
- `manifest.json` : 익스텐션 배포 과정에서 공개 버전이 아닌 베타 버전으로 배포하려고 하였음. 따라서 공식 문서를 참고하여 `manifest.json` 설정을 임시로 변경하였음
- `service_worker.js` : 현재 `syncBookmarkChanges()` 함수는 아직까지 백엔드 연동 테스트를 거치지 않아서 일단은 주석처리를 하여 배포하였음
=> chore: 익스텐션 배포 관련 작업

client/netlify.toml, client/src/api/axiosInstance.js, client/src/api/bookmarkApi.js, client/src/api/testAddBookmark.js, client/src/pages/AuthSuccessPage.jsx, client/src/store/useAuthStore.js
* `_netlify.toml`을 수정하여 https로 요청을 보내도록 명시 => 작동은 배포 후 테스트 해봐야할듯
* API 관련 함수들에서 토큰이 accessToken로 아직 변경되지 않은 문제 해결
=> http관련 문제 및 토큰 관련 문제 해결

client/src/store/useAuthStore.js
=> fix: 토큰 명칭 변경

client/index.html, client/netlify.toml
index.html에 https로 변환하는 메타데이터 추가하여 http로 요청할 시 무조건 https로 변하도록 강제
해당 방법을 사용
https://stackoverflow.com/questions/35178135/how-to-fix-insecure-content-was-loaded-over-https-but-requested-an-insecure-re
=> fix: index.html에 https로 변환하는 메타데이터 추가

client/src/api/bookmarkApi.js
개발자 도구 상에서 `Bearer` prefix이후에 토큰이 바로 붙지 않고 개행이 적용된것으로 보여 토큰에 개행or공백 문자가 적용되지 않도록 `trim`추가
=> fix: 토큰에 trim 적용하도록 수정

client/src/components/bookmark/BookmarkCard.jsx, client/src/components/bookmark/ToggleButton.jsx
Resolve : #77
북마크의 크기가 모니터의 크기에 따라 변하도록 반응형 UI를 적용하였습니다
`BookmarkCard.jsx`와 `ToggleButton.jsx`에서 css변경
어떤 테스트를 했고, 결과가 어땠는지 적어주세요
창 크기에 따라 컴포넌트 사이즈 잘 변함
디자이너가 반응형 작업까지 해놓으면 그때 세부적으로 사이즈 적용 가능할듯
=> 북마크 반응형 UI 적용

server/build.gradle, server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkTreeNode.java, server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java, server/src/main/java/wap/starlist/util/ImageScraper.java
Resolve : #
- `ImageScraper`로 이미지 파싱
- 기존 북마크 생성 로직에 이미지 저장 기능 추가
- 
-
=> ImageScraper로 웹페이지의 이미지를 가져와 저장

server/build.gradle, server/src/main/java/wap/starlist/auth/security/TokenAuthenticationFilter.java, server/src/main/java/wap/starlist/config/SwaggerConfig.java
Resolve : #87 
- 편리한 API 테스트를 위해 Swagger를 추가했습니다.
- 라이브러리는 springdoc을 사용했습니다.
- `build.gradle`
- swagger 라이브러리를 추가했습니다.
- `SwaggerConfig.java`
- swagger ui 사용을 위한 설정 파일을 추가했습니다.
-  `TokenAuthenticationFilter.java`
- security 토큰 이슈로 swagger ui가 켜지지 않는 문제가 발생해 관련 코드를 주석 처리했습니다.
=> Swagger 추가

server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java, server/src/main/java/wap/starlist/bookmark/controller/FolderController.java, server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkTreeNode.java, server/src/main/java/wap/starlist/bookmark/dto/response/BookmarkNodeResponse.java, server/src/main/java/wap/starlist/bookmark/repository/FolderRepository.java, server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java, server/src/main/java/wap/starlist/bookmark/service/FolderService.java
Resolve : #
- 클라이언트에서 북마크를 받는 로직 변경으로 모든 북마크를 가져오는게 아니라 특정 폴더의 하위 노드들만 가져오도록 변경
- 
-
=> 특정 폴더의 하위 노드를 가져오는 기능 추가

server/src/main/java/wap/starlist/config/SecurityConfig.java, server/src/main/java/wap/starlist/config/SwaggerConfig.java
- 로그인 없이 swagger를 사용할 수 있도록 security 설정을 추가하였습니다.
- 
-
=> swagger에 접근할 때 로그인 없이 이용 가능

client/src/functions/utils/getNodesByFolderId.js, client/src/functions/utils/getRootNodes.js
Resolve : #
- 현재 북마크, 폴더 데이터를 가져오는 함수에서 API URL 이 잘못 작성되어있어 수정하였습니다.
=> API URL 수정

server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkTreeNode.java
=> 잘못된 dto구조 수정

server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java, server/src/main/java/wap/starlist/bookmark/controller/FolderController.java
- 이전에 수정한 dto구조가 프론트에 제대로 반영되지 않아 발생한 문제였음
Resolve : #
- 
-
=> feat: api 메서드에 요청 정보를 확인할 수 있는 로그 추가

client/src/pages/AuthSuccessPage.jsx
- `AuthSuccessPage` : 해당 페이지에서 chrome 변수를 선언하여 hrome API 를 쓰도록 수정하였습니다.
=> chrome API 호출 리팩토링

client/src/App.jsx, client/src/components/remainder/RemindCarousel.jsx, client/src/functions/hooks/useRemindBookmarks.js, client/src/pages/MainPage.jsx
리마인드 API호출에 실패시 지속해서 fetch 시도가 일어났던 문제를 해결하였습니다.
- `useRemindBookmarks.js`: retry 속성을 0으로 만들어 한번 실패시 재시도가 일어나지 않게 함
=> 지속해서 fetch 시도하는 문제 해결

client/src/App.jsx
=> startPage 실수 고치기

server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java, server/src/main/java/wap/starlist/bookmark/controller/FolderController.java, server/src/main/java/wap/starlist/bookmark/service/FolderService.java, server/src/main/java/wap/starlist/error/ErrorCode.java, server/src/main/java/wap/starlist/error/ErrorResponse.java, server/src/main/java/wap/starlist/error/GlobalExceptionHandler.java, server/src/main/java/wap/starlist/error/exception/BaseException.java, server/src/main/java/wap/starlist/error/exception/BookmarkNotFoundException.java, server/src/main/java/wap/starlist/error/exception/NotFoundException.java, server/src/main/java/wap/starlist/error/exception/TopFoldersNotFoundException.java
Resolve : #
- 3001 에러 코드를 보내 클라이언트에서 사용자의 동기화 여부를 확인할 수 있다.
=> 최상위 폴더가 없는 경우 3001 에러 응답을 보내는 기능 추가

client/src/components/CardList/CardsContainer.jsx
Resolve : #
- `CardsContainer` 의 `map()` 함수의 key 를 id 에서 index 로 변경하였습니다.
=> CardsContainer map 함수의 key 변경

server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkTreeNode.java
- 기존엔 빌더에 값 할당이 없어서 제대로 저장되지 않았음
Resolve : #
- `dateLastUsed`가 할당되지 않아서 리마인드 개발하는데 어려움이 있을 것으로 보임..
- 그래서 해당 필드를 채우도록 수정하였음
=> 북마크 dateLastUsed, syncing 필드를 채우도록 변경

client/src/components/cardlist/AddButton.jsx, client/src/components/cardlist/BookmarkCard.jsx, client/src/components/cardlist/BreadCrumb.jsx, client/src/components/cardlist/CardList.jsx, client/src/components/cardlist/CardsContainer.jsx, client/src/components/cardlist/FolderCard.jsx, client/src/components/cardlist/SearchBar.jsx, client/src/components/cardlist/ToggleButton.jsx, client/src/components/cardlist/Toolbar.jsx, client/src/pages/MainPage.jsx
`git config core.ignorecase false` 명령어를 사용하여
폴더명의 대소문자를 변경하였을 때 인식하지 못하던 문제를 해결
=> cardlist 폴더 명 변경

client/src/components/cardlist/CardsContainer.jsx, client/src/functions/utils/fetchNodesByPath.js, client/src/functions/utils/getRootNodes.js
Resolve : #
- 백엔드 API 호출에 대한 응답 객체 구조에 맞게 파싱하여 사용할 수 있도록 코드를 수정하였습니다.
=> fix: 백엔드 API 호출 에러 구조에 맞게 코드 변경

client/src/functions/utils/getRootNodes.js, client/src/pages/AuthSuccessPage.jsx
Resolve : #
- 브라우저별로 chrome.runtime.api 를 지원하지 않는 경우가 있어서 이를 수정하였습니다.
=> chrome api 호출을 위해 runtime 확인

client/src/functions/utils/getRootNodes.js
- 잘못된 메시지 타입을 입력하고 있어 이를 수정하였습니다.
=> fix: 메시지 타입 오류 수정

server/src/main/java/wap/starlist/bookmark/controller/FolderController.java, server/src/main/java/wap/starlist/bookmark/dto/response/FolderTreeNode.java, server/src/main/java/wap/starlist/bookmark/service/FolderService.java
=> 폴더 구조를 반환하는 api 구현

client/src/components/remainder/RemindCarousel.jsx
Resolve : #106 
리마인드 글자의 위치를 조정
=> chore: 리마인더 타이틀 위치 수정

client/src/functions/hooks/useFolderTree.js
Resolve : #144
폴더 트리 받아오는 로직 수정
=> feat: 폴더 구조 받아오기 처리 수정

client/src/components/modal/AddItemModal.jsx, client/src/components/modal/DropDown.jsx, client/src/functions/hooks/useFolderTree.js
=> chore: 렌더링 유지

server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkTreeNode.java, server/src/main/java/wap/starlist/bookmark/dto/response/BookmarkNodeResponse.java, server/src/main/java/wap/starlist/bookmark/dto/response/SearchResponse.java, server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
Resolve : #
- 기존 dto에 이미지 url을 담지 않던 문제를 해결
- 
-
=> 스크랩한 이미지 URL을 클라이언트에게 전송하도록 수정

server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java, server/src/main/java/wap/starlist/bookmark/repository/BookmarkRepository.java, server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java, server/src/test/java/wap/starlist/bookmark/service/BookmarkServiceTest.java
=> refactor: 북마크 중복 확인 로직 수정(미완)

server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
- 폴더의 이미지를 가져오려던 코드를 북마크의 이미지를 가져오도록 수정
Resolve : #
- 
-
=> fix: collectNode에서 북마크의 이미지를 scrap하도록 수정

client/src/components/modal/AddBookmarkModal.jsx, client/src/components/modal/AddItemModal.jsx, client/src/components/modal/DropDown.jsx, client/src/functions/hooks/useFolderTree.js
- 모달 창 오류 해결을 위해 디버깅용 콘솔 로그를 추가
=> feat: 디버깅용 콘솔 로그 추가

client/src/components/modal/AddItemModal.jsx, client/src/functions/hooks/useFolderTree.js
Resolve : #144
- 계속 절대경로가 아니라 상대경로로 요청하려고 했었던걸 절대경로로 바꿈
=> 폴더 트리 받아오는 문제 해결

client/src/components/cardlist/CardsContainer.jsx, client/src/components/cardlist/FolderCard.jsx, client/src/functions/hooks/useSearchNodes.js, client/src/functions/hooks/useSearchStore.js, client/src/functions/hooks/useSelectedCardsStore.js, client/src/functions/utils/getNodesBySearch.js
- 키워드를 사용한 GET 요청을 하기 위한 함수를 추가하였습니다. 이때 최종 fetch 를 위한 함수는 `fetchNodesByPath` 를 사용하고 path 값은 `getNodesBySearch` 에서 처리하여 호출합니다.
-  해당 결과를 키워드를 key 로 사용하여 캐싱하되, 키워드는 너무나도 방대하므로 캐싱하는 시간 자체를 짧게 설정하여 메모리 낭비를 방지하였습니다.
- Toolbar 에 SearchBar 가 존재하는데 여기에 입력된 값을 알기 위해서는 Zustand 전역 상태를 사용했으며 이를 `useSearchStore` 에서 처리하도록 하였습니다. 실제로 SearchBar 에서 검색 시간 & 검색 종료에 따른 `setKeyword` 와 `clear`를 설정하기 하면 됩니다. 
- `CardsContainer` 에서는 `useSearchStore` 에 저장된 전역 상태를 구독하고 있으므로 이 값이 변경되면 재렌더링이 일어납니다. 이때, "검색창을 사용하고 있는가?" 에 따라서 `useGetNodes` 와 `useSearchNodes` 를 둘 중 하나를 선택하여 사용합니다. 만약에 이런 분기 처리 과정이 없다면 렌더링될 때마다 불필요하게 2개의 함수를 실행하게 되므로 렌더링 속도를 낮출 수 있습니다. 이를 방지하도록 분기 처리를 설정하였습니다. 
- 결과적으로 응답 결과에 따른 UI 처리는 두 함수 동일하게 사용하므로 UI 렌더링 코드 또한 재사용할 수 있습니다.  
- `CardsContainer.jsx` : 검색 기능을 사용할 수 있게끔 수정
- `useSearchNodes.js` : …
=> 검색 기능을 위한 훅 추가 및 적용

client/src/functions/utils/addBookmarkApi.js, client/src/functions/utils/getRemindBookmarks.js
=> api 관련함수들 일관성 있도록 수정

server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java
Resolve : #
- 불필요한 Import를 제거했습니다.
- `BookmarkController` 클래스
- `import wap.starlist.bookmark.dto.response.SearchResponse;` 삭제
=> 불필요한 import 제거

client/src/components/cardlist/AddButton.jsx, client/src/components/cardlist/AddSelectMenu.jsx, client/src/components/cardlist/SearchBar.jsx, client/src/components/modal/AddBookmarkModal.jsx, client/src/components/modal/AddFolderModal.jsx, client/src/components/modal/AddItemModal.jsx, client/src/components/modal/DropDown.jsx, client/tailwind.config.js
- 검색창, 추가 버튼에 반응형 적용
- 모달 관련 컴포넌트들에 주석 추가
=> css 일부 수정 및 모달 관련 컴포넌트들 주석 추가

client/src/components/cardlist/AddButton.jsx, client/src/components/modal/AddItemModal.jsx
=> 모달창 css 수정

client/src/components/modal/AddFolderModal.jsx, client/src/components/modal/AddItemModal.jsx
Resolve : #144 
모달창의 전반적인 정렬과 여백을 수정하였습니다
=> 모달창 여백, 정렬 css수정

client/src/components/modal/AddItemModal.jsx, client/src/components/modal/DropDown.jsx
Resolve : #144
- 드롭다운의 css를 변경하였습니다
- 
-
=> chore: 드롭다운 css변경

client/src/components/modal/DropDown.jsx
Resolve : #144
- 드롭다운 클릭시 따로 창이 나오는게 아닌 아코디언 형식의 css적용
=> 모달창 아코디언 css

client/src/components/modal/DropDown.jsx
Resolve : #144
- 아코디언의 각 폴더 목록의 크기를 같게 함
=> chore: 아코디언 크기 수정

client/src/components/cardlist/ScrollToTopButton.jsx, client/src/pages/MainPage.jsx
- 페이지의 상단으로 바로 이동가능한 버튼 추가
- `ScrollToTopButton.jsx`: 상단으로 이동하게 해주는 버튼 컴포넌트. window.scrollTo({ top: 0, behavior: "smooth" })를 사용하여 페이지의 상단으로 바로 이동가능하게 하였다.
UI 작업일 경우, 변경된 화면 캡처를 첨부해주세요
=> 상단 이동 버튼 추가

server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
=> Stopwatch를 사용해 속도측정 후 로그 작성

server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java, server/src/main/java/wap/starlist/bookmark/domain/Bookmark.java, server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkEditRequest.java, server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkMoveRequest.java, server/src/main/java/wap/starlist/bookmark/repository/BookmarkRepository.java, server/src/main/java/wap/starlist/bookmark/repository/FolderRepository.java, server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java
- 여러 개의 폴더와 북마크를 다른 폴더로 이동시킬 수 있도록 변경
- 기존엔 하나의 북마크만 폴더로 이동시킬 수 있었지만, 요청 dto를 변경하였고 쿼리 하나로 요청을 반영하도록 하였다.
=> 여러 개의 북마크와 폴더를 이동할 수 있도록 변경

client/src/assets/index.js, client/src/components/startPageComponents/MockUp.jsx
- svg 경로가 잘못되어 배포가 안되는 오류 해결
- 제발되어라
=> chore: svg파일명 오류 수정

client/src/components/startPageComponents/Slider.jsx
=> chore: 클립 이미지 잘린거 수정

server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java, server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkTreeNode.java, server/src/main/java/wap/starlist/bookmark/repository/BookmarkRepository.java, server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java, server/src/main/resources/application.yml
Resolve : #
- 사용자가 3개월동안 열람하지 않은 북마크 15개를 보여줌
- 리마인드 끄기 기능 활성화
- 북마크가 리마인드된 시각은 리마인드 북마크를 가져오는데 영향을 끼치지 않습니다.
-
=> 리마인드 북마크를 보여주도록 변경

server/src/main/java/wap/starlist/bookmark/domain/Folder.java
Resolve : #
- 폴더 추가 시 googleId 할당이 필수가 아니도록 변경
- 
-
=> 폴더 생성시 googleId가 필수가 아니도록 변경

server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java, server/src/main/java/wap/starlist/bookmark/domain/Bookmark.java, server/src/main/java/wap/starlist/bookmark/repository/BookmarkRepository.java, server/src/main/java/wap/starlist/bookmark/service/BookmarkService.java, server/src/main/java/wap/starlist/error/ErrorCode.java
Resolve : #
- 자신이 소유하지 않은 북마크가 리마인드 되는 버그 수정
- 
-
=> 사용자의 북마크 중에서 리마인드를 보여주도록 변경

client/src/functions/utils/getRemindBookmarks.js
- 테스트 용으로 변경해놓았던 getRemindBookmarks.js 함수를 다시 복구
- 
-
=> 리마인드 Api 관련 함수 복구

client/src/components/cardlist/CardsContainer.jsx, client/tailwind.config.js
Resolve : #
- 카드 컨테이너에 최소 높이를 지정하여 북마크 혹은 폴더만 출력될 시에 높이가 압축되던 오류를 수정
- 
-
=> chore:카드 리스트 최소 높이 지정

client/src/components/cardlist/CardsContainer.jsx, client/tailwind.config.js
Resolve : #
- 카드 리스트의 gap을 수정하여 창이 올라가는 오류 해결?
=> chore: gap 조절

client/src/assets/cards/folder-normal.svg, client/src/components/cardlist/CardsContainer.jsx, client/src/components/cardlist/FolderCard.jsx, client/src/components/remainder/RemindCard.jsx
Resolve : #
- 폴더 svg를 수정해서 
- 
-
=> chore:폴더 svg 수정

client/src/pages/MainPage.jsx
=> chore:메인페이지 수정

client/src/components/modal/AddItemModal.jsx, client/src/components/remainder/RemindCard.jsx, client/src/components/remainder/RemindCarousel.jsx
- 카드 컴포넌트에 그림자 추가
- 리마인드 북마크가 없을 경우 멘트 변경
=> 캐러셀 css일부수정

client/src/functions/utils/deleteNodes.js, client/src/functions/utils/editBookmark.js, client/src/functions/utils/editFolder.js, client/src/functions/utils/moveNodes.js
- 현재 북마크/폴더 이동 & 삭제 & 변경 을 처리하는 함수에서 잘못된 주소로 백엔드에 접근하고 있어 오류가 발생하였습니다. 해당 함수에서 사용하는 `API_BASE_URL` 에 오타가 있어 이를 수정하였습니다.
=> API URL 오타 수정

client/src/components/remainder/RemindCard.jsx, client/src/components/remainder/RemindCarousel.jsx, client/src/functions/utils/patchRemindDisable.js, client/src/pages/SettingPage.jsx
- 리마인더 북마크에서 삼점 버튼을 누르면 해당 리마인드가 다시 보이지 않도록 함
- 
-
=> feat:리마인드 제거 테스트

server/src/main/java/wap/starlist/config/SecurityConfig.java
Resolve : #
- PATCH 요청에 대한 cors 설정이 되지않아 수정하였습니다.
- 
-
=> PATCH 요청이 cors가 발생하지 않도록 수정

client/src/functions/utils/patchRemindDisable.js
Resolve : #
- 엔드 포인트 경로를 수정
- 
-
=> chore: 리마인드 제거 api 관련 수정

server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java, server/src/main/java/wap/starlist/bookmark/dto/request/BookmarkMoveRequest.java
=> moveRequest를 로그로 확인

server/src/main/java/wap/starlist/bookmark/controller/BookmarkController.java
Resolve : #
- 요청 dto를 받을 때 `@RequestBody`어노테이션이 없어서 요청이 null이 되던 문제 해결
- 
-
=> 요청 dto를 받기 위해 @RequestBody 어노테이션 추가

client/src/components/remainder/RemindCard.jsx, client/src/functions/utils/getRemindBookmarks.js
Resolve : #
- 리마인드 북마크를 더 이상 띄우지 않게하는 버튼의 ui를 수정
- 팝업창 외부를 클릭시 해당 팝업창이 꺼지도록 수정
=> chore:리마인드 제거 팝업 수정

client/src/components/remainder/RemindCarousel.jsx, client/src/functions/utils/getRemindBookmarks.js
=> 캐러셀 오류 수정2

client/src/components/remainder/RemindCarousel.jsx, client/src/functions/utils/getRemindBookmarks.js
Resolve : #
- 리마인더에서 더 이상 보여지지 않도록 비활성화한 북마크가 캐러셀에 더 이상 남아있지 않도록 수정
- 
-
=> chore:비활성화한 북마크가 캐러셀에 제외하도록 함

client/src/components/remainder/RemindCarousel.jsx, client/src/functions/utils/getRemindBookmarks.js
- 리마인드 북마크가 5개 이하일시 네비게이션 바를 눌렀을 때 한쪽으로 무한하게 늘어나는 문제를 해결
- 지금은 북마크가 5개 이하일 시 그 갯수만큼만 출력하도록 함
- 5개 이하일 시 해당 북마크들을 반복하여 출력하도록 하는 부분은 구현 과정에서 문제가 계속 발생하여 후에 수정 예정
- 
-
=> 리마인드 북마크가 5개 이하인경우 무한히 증식하는 에러 수정(임시)

client/src/components/startPageComponents/Slider.jsx, client/src/pages/StartPage.jsx
- lazy를 적용하여 시작페이지의 성능을 향상 시도
- `StartPage.jsx`와 목업창의 `Slider.jsx`의 이미지에 lazy를 적용하여 지금 당장에 필요하지 않은 요소들을 지연로드하도록 하였습니다.
=> 시작페이지 lazy 적용

client/src/functions/utils/getRemindBookmarks.js
=> 테스트용 API로 설정해놓은거 복구

client/package.json, client/src/components/cardlist/CardsContainer.jsx, client/src/components/remainder/RemindCarousel.jsx, client/src/functions/utils/getRemindBookmarks.js, client/src/functions/utils/getRootNodes.js, client/src/pages/AuthSuccessPage.jsx, client/src/pages/MainPage.jsx, client/yarn.lock
- 리마인더 캐러샐, 카드 리스트 영역에 로딩, 에러 UI 를 추가하였습니다.
- 로딩 UI 는 현재 `react-spinners` 라이브러리를 사용하고 있습니다.
=> 로딩, 에러 UI 추가

client/src/components/remainder/RemindCard.jsx
- 리마인드 안보이게 하기 팝업 창의 border값을 수정하였습니다.
=> 리마인드 팝업 창 rounded수정

client/src/components/reminder/RemindCarousel.jsx
=> fix: 리마인드 refetch 설정

client/src/components/modal/AddFolderModal.jsx, client/src/functions/apis/addBookmark.js
- 폴더 추가를 userid가 아니라 folderid로 하도록 변경
=> chore:폴더 추가 요청 변경

client/src/components/modal/AddFolderModal.jsx, client/src/functions/apis/addBookmark.js
=> Revert "chore:폴더 추가 요청 변경"

client/src/components/reminder/RemindCard.jsx
=> feat: 리마인드 카드 디폴트 이미지 추가
